### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by Yordan-Ramchev** [MentorMate/create-vue#62]
**Is your feature request related to a problem? Please describe.**
dependabot.yml

**Describe the solution you'd like**

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```
